name: portfolio
description: "Manthan Belani - Flutter Developer Portfolio"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.5
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/my_image.png
    - assets/Manthan_CV.pdf
    - assets/project_images/dream_canvas/
    - assets/project_images/housely_real_estate_app/
    - assets/project_images/portal_app/
